### ISSUE TITLE
是否可以更新到最新固件版本

### ISSUE THREAD

**Issue by phorcys** [naivekun/ls3a6000-overclock-firmware#1]
https://github.com/loongson/Firmware/tree/main/6000Series/PC/XA61200

这里发布的最新固件可以支持RDNA/RDNA2/RDNA3显卡（关闭oprom）

更新下超频固件到这个版本吧。

**Comment by naivekun** [comment]
本周末搞一下

**Comment by naivekun** [comment]
更了
